# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'Youtube' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Youtube
pod 'Google/SignIn'
pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
pod "youtube-ios-player-helper"
pod 'RealmSwift'
pod 'FSPagerView'
pod ‘Kingfisher’
pod 'SnapKit', '~> 3.0.0’

end
